### PR TITLE
Add support for release 2.9

### PR DESCRIPTION
**Pull request by matteodelabre**
This PR replaces our existing strategies for dynamically locating the various functions we need to make rm2fb work with a static lookup table of the addresses of these functions.

We’re making this choice because it seems that we’re spending more time trying to adapt the strategies after each release than we would if we just updated a static list of addresses. This change also gives us the opportunity to check that rm2fb works correctly with an OS release before users get to use it. The cost is that we’ll need to make an update after each OS release.

To test, you’ll need to move the `offsets` file in the `src/` folder to `/opt/share/rm2fb/offsets` on the tablet (the parent directory needs to be created).

### CODE REVIEW

**Comment by raisjn** [comment]
thank you for making this diff! the approach seems reasonable - it seems like we can get updates for a release done within a week or so using this one (assuming that someone knowledgeable will be able to add the signatures). 

my pieces of feedback are:

1. what will the process for adding new signatures be? committing to toltec or this repo? 
2. should the server statically compile in known signatures (so we don't need an extra file) and allow overrides via text file? (or is this too much work?)
3. we will need to add some docs to this repo (minimal is fine) about this new file or make an issue and link to it (so people can find more info)

**Comment by matteodelabre** [comment]
Thanks for the feedback!

> 1. what will the process for adding new signatures be? committing to toltec or this repo?

I’d say it’s best to keep the signatures in this repo so that those who don’t use Toltec can still install and use rm2fb fairly easily.

> 2. should the server statically compile in known signatures (so we don't need an extra file) and allow overrides via text file? (or is this too much work?)

Yeah it would make sense to bundle signatures in the binary, especially for manual installs. It shouldn’t be too hard to accomplish, I’ll look into it.

> 3. we will need to add some docs to this repo (minimal is fine) about this new file or make an issue and link to it (so people can find more info)

Yes, good point! I’ll look into it too.

**Comment by matteodelabre** [comment]
Tested on versions 2.8 and 2.9 beta.

**Comment by hunt529** [comment]
@matteodelabre -- I am not a developer but I am a user of Remarkable2 + KO Reader (which fully depends on rm2fb) and your continued updating/efforts.  I just wanted to express appreciating for what you are doing.

I recently upgraded to 2.9 beta -- and am looking forward to getting my KO Reader back :)

**Comment by matteodelabre** [comment]
Hi @hunt529! Of course, as you may know, I’m not the only one working on rm2fb. But thank you for your support, and I’m glad you find the project useful!

@raisjn Do you think we can merge this?

**Review by raisjn — APPROVED** [review]
shipit

the updateType is a little new to me, but seems fine

**Comment by matteodelabre** [comment]
@raisjn Yep, updateType is used to select between the two possible signatures of the `update` function, since its signature was changed from `void (*)(int, int, int, int, int, int)` to `void (*)(QRect&, int, int)` in release 2.9 beta.

**Pull request merged**
