### PR TITLE
Add support for 2.15.0.1046 and 2.15.0.1052

### PR DESCRIPTION
**Pull request by rotech**

### CODE REVIEW

**Comment by Eeems** [comment]
Looks like this is also adding support for 2.15.0.1052, which isn't reflected in the title.

**Comment by rotech** [comment]
Sorry, just added the new version like 2 minutes ago, as the first wasn't merged.  Not sure how to do this properly, do I make another pull request with both versions and close this one?

**Comment by Eeems** [comment]
I'd just recommend updating the pull request title.

**Comment by rotech** [comment]
Yeah, right that makes lots of sense.  Didn't know I could do that, still learning.

**Pull request merged**
